///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DesktopAppTest
{
    public partial class BtnSubmit
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Mouse_Click_BtnSubmit(RepoItemInfo buttonInfo)
        {
        	//raise a warning message instead of an information
            Report.Log(ReportLevel.Warn, "Mouse", "Mouse Left Click item 'buttonInfo' at Center.", buttonInfo);
            
            //Performing the clicking action
            buttonInfo.FindAdapter<Button>().Click();
            
            // Insert a small delay
            Report.Log(ReportLevel.Info, "waiting for two seconds");
            Delay.Seconds(2);
        }

    }
}
