///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DesktopAppTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DesktopAppTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("867436f5-3985-4948-a01f-6970bc0a91b3")]
    public partial class DesktopAppTestRepository : RepoGenBaseFolder
    {
        static DesktopAppTestRepository instance = new DesktopAppTestRepository();
        DesktopAppTestRepositoryFolders.RxMainFrameAppFolder _rxmainframe;

        /// <summary>
        /// Gets the singleton class instance representing the DesktopAppTestRepository element repository.
        /// </summary>
        [RepositoryFolder("867436f5-3985-4948-a01f-6970bc0a91b3")]
        public static DesktopAppTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DesktopAppTestRepository() 
            : base("DesktopAppTestRepository", "/", null, 0, false, "867436f5-3985-4948-a01f-6970bc0a91b3", ".\\RepositoryImages\\DesktopAppTestRepository867436f5.rximgres")
        {
            _rxmainframe = new DesktopAppTestRepositoryFolders.RxMainFrameAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("867436f5-3985-4948-a01f-6970bc0a91b3")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("90e6adfc-3c3d-4123-95c9-e28ba2931ba2")]
        public virtual DesktopAppTestRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class DesktopAppTestRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("90e6adfc-3c3d-4123-95c9-e28ba2931ba2")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            DesktopAppTestRepositoryFolders.RxTabIntroductionFolder _rxtabintroduction;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "90e6adfc-3c3d-4123-95c9-e28ba2931ba2", "")
            {
                _rxtabintroduction = new DesktopAppTestRepositoryFolders.RxTabIntroductionFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("90e6adfc-3c3d-4123-95c9-e28ba2931ba2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("90e6adfc-3c3d-4123-95c9-e28ba2931ba2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RxTabIntroduction folder.
            /// </summary>
            [RepositoryFolder("e5183518-7587-43a4-be6d-8134727d14b7")]
            public virtual DesktopAppTestRepositoryFolders.RxTabIntroductionFolder RxTabIntroduction
            {
                get { return _rxtabintroduction; }
            }
        }

        /// <summary>
        /// The RxTabIntroductionFolder folder.
        /// </summary>
        [RepositoryFolder("e5183518-7587-43a4-be6d-8134727d14b7")]
        public partial class RxTabIntroductionFolder : RepoGenBaseFolder
        {
            RepoItemInfo _insertnameInfo;
            RepoItemInfo _btnsubmitInfo;
            RepoItemInfo _btnresetInfo;
            RepoItemInfo _validatemessageInfo;

            /// <summary>
            /// Creates a new RxTabIntroduction  folder.
            /// </summary>
            public RxTabIntroductionFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabIntroduction", "?/?/tabpage[@controlname='RxTabIntroduction']", parentFolder, 30000, null, false, "e5183518-7587-43a4-be6d-8134727d14b7", "")
            {
                _insertnameInfo = new RepoItemInfo(this, "InsertName", "?/?/text[@accessiblename='Enter your name']", 30000, null, "2e707e04-a9a3-42d4-9859-10a6d7c537b7");
                _btnsubmitInfo = new RepoItemInfo(this, "BtnSubmit", "button[@controlname='btnSubmitUserName']", 30000, null, "ba91cd16-ddeb-434c-9017-a3008cea45ba");
                _btnresetInfo = new RepoItemInfo(this, "BtnReset", "link[@controlname='RxLinkBtnReset']/?/?/link[@accessiblename='Reset']", 30000, null, "1d155b2f-c8ac-44e5-b7f4-d6d4b8c973a2");
                _validatemessageInfo = new RepoItemInfo(this, "ValidateMessage", "text[@controlname='lblWelcomeMessage']", 30000, null, "a8ec0e63-bd06-42ab-a888-c877e2ac1d7d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e5183518-7587-43a4-be6d-8134727d14b7")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e5183518-7587-43a4-be6d-8134727d14b7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The InsertName item.
            /// </summary>
            [RepositoryItem("2e707e04-a9a3-42d4-9859-10a6d7c537b7")]
            public virtual Ranorex.Text InsertName
            {
                get
                {
                    return _insertnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The InsertName item info.
            /// </summary>
            [RepositoryItemInfo("2e707e04-a9a3-42d4-9859-10a6d7c537b7")]
            public virtual RepoItemInfo InsertNameInfo
            {
                get
                {
                    return _insertnameInfo;
                }
            }

            /// <summary>
            /// The BtnSubmit item.
            /// </summary>
            [RepositoryItem("ba91cd16-ddeb-434c-9017-a3008cea45ba")]
            public virtual Ranorex.Button BtnSubmit
            {
                get
                {
                    return _btnsubmitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSubmit item info.
            /// </summary>
            [RepositoryItemInfo("ba91cd16-ddeb-434c-9017-a3008cea45ba")]
            public virtual RepoItemInfo BtnSubmitInfo
            {
                get
                {
                    return _btnsubmitInfo;
                }
            }

            /// <summary>
            /// The BtnReset item.
            /// </summary>
            [RepositoryItem("1d155b2f-c8ac-44e5-b7f4-d6d4b8c973a2")]
            public virtual Ranorex.Link BtnReset
            {
                get
                {
                    return _btnresetInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The BtnReset item info.
            /// </summary>
            [RepositoryItemInfo("1d155b2f-c8ac-44e5-b7f4-d6d4b8c973a2")]
            public virtual RepoItemInfo BtnResetInfo
            {
                get
                {
                    return _btnresetInfo;
                }
            }

            /// <summary>
            /// The ValidateMessage item.
            /// </summary>
            [RepositoryItem("a8ec0e63-bd06-42ab-a888-c877e2ac1d7d")]
            public virtual Ranorex.Text ValidateMessage
            {
                get
                {
                    return _validatemessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ValidateMessage item info.
            /// </summary>
            [RepositoryItemInfo("a8ec0e63-bd06-42ab-a888-c877e2ac1d7d")]
            public virtual RepoItemInfo ValidateMessageInfo
            {
                get
                {
                    return _validatemessageInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
